require('dotenv').config();
const express=require('express'), http=require('http'), path=require('path'), fs=require('fs'), crypto=require('crypto'), axios=require('axios'), sqlite3=require('sqlite3').verbose(), multer=require('multer'), sharp=require('sharp'), QRCode=require('qrcode'), pino=require('pino'), cron=require('node-cron');
const {Server}=require('socket.io');
const baileys=require('@whiskeysockets/baileys');
const app=express(), server=http.createServer(app), io=new Server(server);
const PORT=Number(process.env.PORT||3000), DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data'), UP=path.join(DATA_DIR,'uploads'), SESSION=path.join(DATA_DIR,'whatsapp-session'), CAMPAIGN_DIR=path.join(DATA_DIR,'campanhas');
for(const p of [DATA_DIR,UP,path.join(UP,'antes'),path.join(UP,'depois'),path.join(UP,'montagens'),CAMPAIGN_DIR,SESSION]) fs.mkdirSync(p,{recursive:true});
const db=new sqlite3.Database(path.join(DATA_DIR,'harmony.sqlite'));
const run=(sql,p=[])=>new Promise((res,rej)=>db.run(sql,p,function(e){e?rej(e):res(this)})); const get=(sql,p=[])=>new Promise((res,rej)=>db.get(sql,p,(e,r)=>e?rej(e):res(r))); const all=(sql,p=[])=>new Promise((res,rej)=>db.all(sql,p,(e,r)=>e?rej(e):res(r)));
const slots=['07:00','08:30','10:00','13:00','14:30','16:00'];
const TZ='America/Bahia', PAY_NOW='pix_agora', PAY_AFTER='pix_depois';
let sock=null, connected=false, qrData='';
let settings={};
function brl(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} function num(j){return String(j||'').split('@')[0].replace(/\D/g,'')} function jid(n){return String(n).replace(/\D/g,'')+'@s.whatsapp.net'}
function keyBuffer(){const file=path.join(DATA_DIR,'config.key');if(!fs.existsSync(file))fs.writeFileSync(file,crypto.randomBytes(32),{mode:0o600});return fs.readFileSync(file)}
function seal(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',keyBuffer(),iv),body=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]),tag=cipher.getAuthTag();return Buffer.concat([iv,tag,body]).toString('base64')}
function open(value){try{const b=Buffer.from(value,'base64'),iv=b.subarray(0,12),tag=b.subarray(12,28),body=b.subarray(28),dec=crypto.createDecipheriv('aes-256-gcm',keyBuffer(),iv);dec.setAuthTag(tag);return Buffer.concat([dec.update(body),dec.final()]).toString('utf8')}catch{return ''}}
function passwordHash(password,salt){return crypto.scryptSync(password,salt,64).toString('hex')}
async function loadSettings(){const rows=await all('SELECT chave,valor FROM configuracoes');settings=Object.fromEntries(rows.map(x=>[x.chave,open(x.valor)]));return settings}
async function saveSetting(key,value){await run('INSERT OR REPLACE INTO configuracoes(chave,valor) VALUES(?,?)',[key,seal(value)]);settings[key]=String(value)}
function isoBahia(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
function addDays(date,days){const d=new Date(date+'T12:00:00-03:00');d.setDate(d.getDate()+days);return isoBahia(d)}
function dateFromParts(year,month,day){return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
function nthWeekday(year,month,weekday,n){const d=new Date(Date.UTC(year,month-1,1,12));const delta=(weekday-d.getUTCDay()+7)%7;d.setUTCDate(1+delta+(n-1)*7);return isoBahia(d)}
function easterDate(year){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return dateFromParts(year,month,day)}
function campaignDates(year){const easter=easterDate(year);return {ano_novo:dateFromParts(year,1,1),carnaval:addDays(easter,-47),pascoa:easter,dia_maes:nthWeekday(year,5,0,2),dia_namorados:dateFromParts(year,6,12),sao_joao:dateFromParts(year,6,24),ferias:dateFromParts(year,7,1),dia_pais:nthWeekday(year,8,0,2),primavera:dateFromParts(year,9,22),dia_criancas:dateFromParts(year,10,12),black_friday:addDays(nthWeekday(year,11,4,4),1),natal:dateFromParts(year,12,25),reveillon:dateFromParts(year,12,31)}}
const CAMPAIGNS=[
 {id:'ano_novo',nome:'Ano-Novo',dias:6,texto:'✨ Ano novo, carro renovado! Comece o ano com seu veículo limpo e bem cuidado, sem sair de casa.'},
 {id:'carnaval',nome:'Carnaval',dias:7,texto:'🎉 Vai curtir o Carnaval? Deixe seu carro brilhando antes da folia.'},
 {id:'pascoa',nome:'Páscoa',dias:7,texto:'🐰 Nesta Páscoa, presenteie seu carro com aquele cuidado especial.'},
 {id:'dia_maes',nome:'Dia das Mães',dias:7,texto:'💐 Mãe merece praticidade e carinho. Presenteie com uma lavagem completa.'},
 {id:'dia_namorados',nome:'Dia dos Namorados',dias:5,texto:'❤️ Seu encontro merece um carro limpo e bem cuidado. Reserve seu horário.'},
 {id:'sao_joao',nome:'São João',dias:7,texto:'🌽 O São João chegou! Antes dos festejos, deixe seu carro limpo e preparado.'},
 {id:'ferias',nome:'Férias de Julho',dias:7,texto:'🧳 Vai viajar nas férias? Comece o passeio com o carro limpo por dentro e por fora.'},
 {id:'dia_pais',nome:'Dia dos Pais',dias:7,texto:'💙 Neste Dia dos Pais, dê um presente útil: o carro dele limpo e renovado.'},
 {id:'primavera',nome:'Primavera',dias:5,texto:'🌼 Primavera chegando, carro brilhando! Renove o visual do seu veículo.'},
 {id:'dia_criancas',nome:'Dia das Crianças',dias:5,texto:'👨‍👩‍👧‍👦 Passeio com a família combina com carro limpo e confortável.'},
 {id:'black_friday',nome:'Black Friday',dias:7,texto:'🖤 Black Friday Harmony Car Wash! Condição especial por tempo limitado.'},
 {id:'natal',nome:'Natal',dias:10,texto:'🎄 Seu carro também merece ficar bonito para as festas. Garanta seu horário de Natal.'},
 {id:'reveillon',nome:'Réveillon',dias:6,texto:'🎆 Entre no ano novo com o carro limpo e renovado. Últimos horários de dezembro.'}
];
async function ensureColumn(table,column,definition){const cols=await all(`PRAGMA table_info(${table})`);if(!cols.some(x=>x.name===column))await run(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`)}
async function init(){
 await run(`CREATE TABLE IF NOT EXISTS clientes(id INTEGER PRIMARY KEY AUTOINCREMENT, whatsapp TEXT UNIQUE, nome TEXT, casa TEXT, documento TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await run(`CREATE TABLE IF NOT EXISTS veiculos(id INTEGER PRIMARY KEY AUTOINCREMENT, cliente_id INTEGER, modelo TEXT, cor TEXT)`);
 await run(`CREATE TABLE IF NOT EXISTS servicos(id INTEGER PRIMARY KEY, nome TEXT, descricao TEXT, preco REAL, ativo INTEGER DEFAULT 1)`);
 await run(`CREATE TABLE IF NOT EXISTS agendamentos(id INTEGER PRIMARY KEY AUTOINCREMENT, cliente_id INTEGER, veiculo_id INTEGER, servico_id INTEGER, data TEXT, horario TEXT, status TEXT DEFAULT 'aguardando_pagamento', payment_id TEXT, pagamento_status TEXT DEFAULT 'pending', foto_antes TEXT, foto_depois TEXT, montagem TEXT, autoriza_divulgacao INTEGER DEFAULT 0, inicio TEXT, fim TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(data,horario))`);
 await run(`CREATE TABLE IF NOT EXISTS sessoes(whatsapp TEXT PRIMARY KEY, etapa TEXT, dados TEXT)`);
 await ensureColumn('agendamentos','forma_pagamento',`TEXT DEFAULT '${PAY_NOW}'`);
 await ensureColumn('agendamentos','pix_code','TEXT');
 await ensureColumn('agendamentos','payment_created_at','TEXT');
 await run(`CREATE TABLE IF NOT EXISTS campanhas(id TEXT PRIMARY KEY, nome TEXT NOT NULL, ativo INTEGER DEFAULT 1, antecedencia INTEGER DEFAULT 7, texto TEXT NOT NULL, imagem TEXT, updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await run(`CREATE TABLE IF NOT EXISTS envios_automaticos(chave TEXT PRIMARY KEY, enviado_em TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await run(`CREATE TABLE IF NOT EXISTS configuracoes(chave TEXT PRIMARY KEY, valor TEXT NOT NULL)`);
 await run(`CREATE TABLE IF NOT EXISTS admin_auth(id INTEGER PRIMARY KEY CHECK(id=1), salt TEXT NOT NULL, hash TEXT NOT NULL)`);
 await run(`CREATE TABLE IF NOT EXISTS admin_sessions(token_hash TEXT PRIMARY KEY, expires_at INTEGER NOT NULL)`);
 for(const c of CAMPAIGNS)await run(`INSERT OR IGNORE INTO campanhas(id,nome,ativo,antecedencia,texto) VALUES(?,?,1,?,?)`,[c.id,c.nome,c.dias,c.texto]);
 const count=await get('SELECT COUNT(*) c FROM servicos'); if(!count.c){await run('INSERT INTO servicos VALUES(1,?,?,?,1)',['Express','Lavagem externa, rodas e pneus',35]);await run('INSERT INTO servicos VALUES(2,?,?,?,1)',['Completa','Externa + aspiração + painel + rodas e pneus',55]);await run('INSERT INTO servicos VALUES(3,?,?,?,1)',['Premium','Completa + aspiração detalhada + cera + acabamento de pneus',80]);}
 await loadSettings();
}
async function send(to,text){if(sock&&connected) await sock.sendMessage(to,{text})}
async function menu(to){await send(to,'🚗✨ *HARMONY CAR WASH*\nHarmony Residence\n\nSeu carro limpo sem sair de casa. 🏠\n\n1️⃣ 🧽 LAVAR MEU CARRO\n2️⃣ 💰 SERVIÇOS E PREÇOS\n3️⃣ 📅 MEUS AGENDAMENTOS\n4️⃣ 🚘 MEUS VEÍCULOS\n5️⃣ ☎️ ATENDIMENTO\n\nDigite o número da opção.');}
async function saveSession(w,e,d={}){await run('INSERT OR REPLACE INTO sessoes(whatsapp,etapa,dados) VALUES(?,?,?)',[w,e,JSON.stringify(d)])} async function session(w){const r=await get('SELECT * FROM sessoes WHERE whatsapp=?',[w]);return r?{etapa:r.etapa,dados:JSON.parse(r.dados||'{}')}:null} async function clearSession(w){await run('DELETE FROM sessoes WHERE whatsapp=?',[w])}
async function servicesText(){const s=await all('SELECT * FROM servicos WHERE ativo=1 ORDER BY id');return s.map(x=>`${x.id}️⃣ *${x.nome.toUpperCase()}* — ${brl(x.preco)}\n${x.descricao}`).join('\n\n')}
async function handle(to,text){const w=num(to), t=String(text||'').trim(); if(!t)return; if(/^menu$/i.test(t)){await clearSession(w);return menu(to)}; const s=await session(w);
 if(!s){if(t==='1'){await send(to,'🧽 *ESCOLHA SUA LAVAGEM*\n\n'+await servicesText()+'\n\nDigite 1, 2 ou 3.');return saveSession(w,'servico')}; if(t==='2'){await send(to,'💰 *SERVIÇOS E PREÇOS*\n\n'+await servicesText()+'\n\nDigite *menu* para voltar.');return}; if(t==='3'){const c=await get('SELECT * FROM clientes WHERE whatsapp=?',[w]); if(!c)return send(to,'Você ainda não possui agendamentos. Digite *menu* para começar.'); const a=await all(`SELECT a.*,s.nome,v.modelo,v.cor FROM agendamentos a JOIN servicos s ON s.id=a.servico_id JOIN veiculos v ON v.id=a.veiculo_id WHERE a.cliente_id=? ORDER BY a.data DESC,a.horario DESC LIMIT 10`,[c.id]); return send(to,a.length?'📅 *MEUS AGENDAMENTOS*\n\n'+a.map(x=>`#${x.id} • ${x.data} ${x.horario}\n🚘 ${x.modelo} — ${x.cor}\n🧽 ${x.nome}\n📌 Lavagem: ${x.status}\n💳 Pagamento: ${paymentLabel(x)}`).join('\n\n'):'Nenhum agendamento encontrado.')}; if(t==='4'){const c=await get('SELECT * FROM clientes WHERE whatsapp=?',[w]);const v=c?await all('SELECT * FROM veiculos WHERE cliente_id=?',[c.id]):[];return send(to,v.length?'🚘 *MEUS VEÍCULOS*\n\n'+v.map((x,i)=>`${i+1}️⃣ ${x.modelo} — ${x.cor}`).join('\n'):'Nenhum veículo cadastrado ainda.')}; if(t==='5')return send(to,'☎️ Atendimento Harmony Car Wash.\nEnvie sua dúvida e nossa equipe responderá assim que possível.'); return menu(to)}
 if(s.etapa==='servico'){const sv=await get('SELECT * FROM servicos WHERE id=? AND ativo=1',[Number(t)]);if(!sv)return send(to,'Escolha 1, 2 ou 3.');const c=await get('SELECT * FROM clientes WHERE whatsapp=?',[w]); if(!c){await saveSession(w,'nome',{servicoId:sv.id});return send(to,'👤 Antes de agendar, qual é o seu *nome*?')};const vs=await all('SELECT * FROM veiculos WHERE cliente_id=?',[c.id]);if(vs.length){await saveSession(w,'veiculo_existente',{servicoId:sv.id,veiculos:vs.map(x=>x.id)});return send(to,'🚘 Qual veículo vamos lavar?\n\n'+vs.map((x,i)=>`${i+1}️⃣ ${x.modelo} — ${x.cor}`).join('\n')+`\n${vs.length+1}️⃣ Cadastrar outro veículo`)} await saveSession(w,'modelo',{servicoId:sv.id,clienteId:c.id});return send(to,'🚘 Qual é o *modelo* do seu veículo?')}
 if(s.etapa==='nome'){s.dados.nome=t;await saveSession(w,'casa',s.dados);return send(to,'🏠 Qual é o *número da sua casa*?\nExemplo: 58')}
 if(s.etapa==='casa'){const r=await run('INSERT INTO clientes(whatsapp,nome,casa) VALUES(?,?,?)',[w,s.dados.nome,t]);s.dados.clienteId=r.lastID;await saveSession(w,'modelo',s.dados);return send(to,'🚘 Qual é o *modelo* do seu veículo?')}
 if(s.etapa==='veiculo_existente'){const idx=Number(t)-1, ids=s.dados.veiculos;if(Number(t)===ids.length+1){await saveSession(w,'modelo',s.dados);return send(to,'🚘 Qual é o *modelo* do novo veículo?')}if(idx<0||idx>=ids.length)return send(to,'Escolha uma opção válida.');s.dados.veiculoId=ids[idx];return askDate(to,w,s.dados)}
 if(s.etapa==='modelo'){s.dados.modelo=t;await saveSession(w,'cor',s.dados);return send(to,'🎨 Qual é a *cor* do veículo?')}
 if(s.etapa==='cor'){const c=s.dados.clienteId?{id:s.dados.clienteId}:await get('SELECT * FROM clientes WHERE whatsapp=?',[w]);const r=await run('INSERT INTO veiculos(cliente_id,modelo,cor) VALUES(?,?,?)',[c.id,s.dados.modelo,t]);s.dados.veiculoId=r.lastID;return askDate(to,w,s.dados)}
 if(s.etapa==='data'){if(!/^\d{4}-\d{2}-\d{2}$/.test(t))return send(to,'Envie a data no formato AAAA-MM-DD. Exemplo: 2026-10-06');if(t<isoBahia())return send(to,'⚠️ Escolha uma data de hoje em diante.');s.dados.data=t;const busy=(await all('SELECT horario FROM agendamentos WHERE data=? AND status<>"cancelado"',[t])).map(x=>x.horario);const free=slots.filter(x=>!busy.includes(x));if(!free.length)return send(to,'🚗 Agenda lotada nessa data. Envie outra data.');s.dados.free=free;await saveSession(w,'horario',s.dados);return send(to,'⏰ *HORÁRIOS DISPONÍVEIS*\n\n'+free.map((x,i)=>`${i+1}️⃣ ${x}`).join('\n')+'\n\nEscolha uma opção.')}
 if(s.etapa==='horario'){const h=s.dados.free[Number(t)-1];if(!h)return send(to,'Escolha um horário válido.');s.dados.horario=h;await saveSession(w,'forma_pagamento',s.dados);return send(to,'💳 *COMO DESEJA PAGAR?*\n\n1️⃣ Pagar agora pelo PIX\n2️⃣ Pagar após a lavagem\n\nEscolha uma opção.')}
 if(s.etapa==='forma_pagamento'){if(!['1','2'].includes(t))return send(to,'Escolha 1 para pagar agora ou 2 para pagar após a lavagem.');s.dados.formaPagamento=t==='1'?PAY_NOW:PAY_AFTER;const c=await get('SELECT * FROM clientes WHERE whatsapp=?',[w]);if(c.documento)return createBooking(to,w,s.dados,c,c.documento);await saveSession(w,'documento',s.dados);return send(to,s.dados.formaPagamento===PAY_NOW?'💳 Para gerar o PIX, informe o *CPF/CNPJ do pagador* (somente números).':'💳 Informe o *CPF/CNPJ do pagador* (somente números). O PIX será gerado automaticamente após a lavagem.')}
 if(s.etapa==='documento'){const doc=t.replace(/\D/g,'');if(![11,14].includes(doc.length))return send(to,'CPF deve ter 11 dígitos ou CNPJ 14. Envie somente números.');const c=await get('SELECT * FROM clientes WHERE whatsapp=?',[w]);await run('UPDATE clientes SET documento=? WHERE id=?',[doc,c.id]);return createBooking(to,w,s.dados,c,doc)}
}
async function askDate(to,w,d){await saveSession(w,'data',d);await send(to,'📅 Qual dia deseja lavar?\nEnvie no formato *AAAA-MM-DD*.\nExemplo: 2026-10-06')}
function paymentLabel(a){if(a.pagamento_status==='paid')return '✅ Pago';if(a.pagamento_status==='expired')return '⌛ PIX expirado';if(a.forma_pagamento===PAY_AFTER&&a.status!=='finalizado')return '🕒 Após o serviço';return '⏳ Pendente'}
async function createBooking(to,w,d,c,doc){const sv=await get('SELECT * FROM servicos WHERE id=?',[d.servicoId]);await run('DELETE FROM agendamentos WHERE data=? AND horario=? AND status="cancelado"',[d.data,d.horario]);let ag;const after=d.formaPagamento===PAY_AFTER;try{ag=await run('INSERT INTO agendamentos(cliente_id,veiculo_id,servico_id,data,horario,status,pagamento_status,forma_pagamento,autoriza_divulgacao) VALUES(?,?,?,?,?,?,?,?,1)',[c.id,d.veiculoId,d.servicoId,d.data,d.horario,after?'agendado':'aguardando_pagamento',after?'pending_after_service':'pending',d.formaPagamento])}catch(e){await clearSession(w);await send(to,'⚠️ Esse horário acabou de ser reservado. Digite *menu* e escolha outro.');return}await clearSession(w);const resumo=`🧾 *RESERVA #${ag.lastID}*\n🏠 Casa ${c.casa}\n📅 ${d.data} às ${d.horario}\n🧽 ${sv.nome}\n💰 ${brl(sv.preco)}`;if(after){await send(to,`${resumo}\n\n✅ *AGENDAMENTO CONFIRMADO!*\nPagamento escolhido: após a lavagem. O PIX será enviado quando o serviço for finalizado.`);io.emit('refresh');return}await send(to,`${resumo}\n\n⏳ Gerando PIX...`);await generatePix(ag.lastID,to,doc,true)}
async function generatePix(id,to,doc,expires){
 const a=await booking(id);
 try{
  if(!settings.mercadopago_access_token)throw Error('Configure o Access Token do Mercado Pago no painel');
  const expiration=new Date(Date.now()+(expires?10:1440)*60000).toISOString();
  const body={transaction_amount:Number(a.preco),description:`Harmony Car Wash #${id}`,payment_method_id:'pix',external_reference:`harmony_${id}`,date_of_expiration:expiration,payer:{email:`cliente${id}@example.com`,first_name:a.nome,identification:{type:String(doc).length===14?'CNPJ':'CPF',number:String(doc)}}};
  if(settings.base_url)body.notification_url=`${settings.base_url}/api/webhooks/mercadopago`;
  const r=await axios.post('https://api.mercadopago.com/v1/payments',body,{headers:{'Content-Type':'application/json','Authorization':`Bearer ${settings.mercadopago_access_token}`,'X-Idempotency-Key':`harmony-${id}-${Date.now()}`},timeout:30000});
  const x=r.data,pid=x?.id,code=x?.point_of_interaction?.transaction_data?.qr_code;
  if(!pid||!code)throw Error('Resposta do Mercado Pago incompleta');
  const clean=String(code).replace(/[\r\n\t]/g,'');await run('UPDATE agendamentos SET payment_id=?,pix_code=?,payment_created_at=datetime("now") WHERE id=?',[String(pid),clean,id]);
  try{await send(to,'📋 *PIX Copia e Cola:*');await send(to,clean);await send(to,expires?'⏳ O horário ficará reservado por 10 minutos enquanto aguardamos o pagamento.':'✅ A lavagem foi concluída. Assim que o PIX for confirmado, o pagamento aparecerá como recebido.')}catch(e){console.error('ENVIO PIX',e.message)}
  pollPayment(id,pid,to,expires)
 }catch(e){await run('UPDATE agendamentos SET pagamento_status="error" WHERE id=?',[id]);if(expires)await run('UPDATE agendamentos SET status="cancelado" WHERE id=?',[id]);try{await send(to,expires?'❌ Não foi possível gerar o PIX e o horário foi liberado. Digite *menu* para tentar novamente.':'❌ A lavagem foi concluída, mas não conseguimos gerar o PIX. Nossa equipe fará a cobrança manualmente.')}catch(_){}console.error('MERCADO PAGO',e.response?.data||e.message)}
}
async function checkPayment(id,pid,to){try{if(!settings.mercadopago_access_token)return false;const d=(await axios.get(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(pid)}`,{headers:{'Authorization':`Bearer ${settings.mercadopago_access_token}`},timeout:15000})).data;const st=String(d?.status||'').toLowerCase();if(st!=='approved')return false;const a=await booking(id);await run('UPDATE agendamentos SET pagamento_status="paid",status=? WHERE id=?',[a.status==='finalizado'?'finalizado':'agendado',id]);try{await send(to,`✅ *PAGAMENTO CONFIRMADO!*\n\nPagamento da lavagem #${id} recebido com sucesso. Obrigado! 🚗✨`)}catch(_){}io.emit('refresh');return true}catch(e){return false}}
function pollPayment(id,pid,to,expires=false){let tries=0;const timer=setInterval(async()=>{if(await checkPayment(id,pid,to))return clearInterval(timer);if(++tries>=60){clearInterval(timer);if(expires){const a=await booking(id);if(a&&a.pagamento_status!=='paid'&&a.status==='aguardando_pagamento'){await run('UPDATE agendamentos SET pagamento_status="expired",status="cancelado" WHERE id=?',[id]);await send(to,`⌛ O PIX da reserva #${id} expirou e o horário foi liberado. Digite *menu* para fazer um novo agendamento.`);io.emit('refresh')}}}},10000)}
function groupEnabled(){return connected&&sock&&settings.publicar_grupo==='1'&&settings.whatsapp_group_jid}
function bookingLink(){const configured=String(settings.whatsapp_public_number||'').replace(/\D/g,'');const own=num(sock?.user?.id);const phone=configured||own;return phone?`https://wa.me/${phone}?text=${encodeURIComponent('Olá, quero agendar uma lavagem')}`:''}
async function availableSlots(date){const busy=(await all('SELECT horario FROM agendamentos WHERE data=? AND status<>"cancelado"',[date])).map(x=>x.horario);return slots.filter(x=>!busy.includes(x))}
async function nextAvailableDate(start=isoBahia()){for(let i=0;i<30;i++){const date=addDays(start,i),free=await availableSlots(date);if(free.length)return {date,free}}return null}
async function currentCampaign(date=isoBahia()){const year=Number(date.slice(0,4));for(const c of await all('SELECT * FROM campanhas WHERE ativo=1'))for(const y of [year,year+1]){const target=campaignDates(y)[c.id];if(target&&date>=addDays(target,-Number(c.antecedencia||0))&&date<=target)return {...c,target}}return null}
async function sendGroupMessage(text,imagePath){if(!groupEnabled())return false;const content=imagePath&&fs.existsSync(imagePath)?{image:fs.readFileSync(imagePath),caption:text}:{text};await sock.sendMessage(settings.whatsapp_group_jid,content);return true}
async function sendScheduledAd(slot){const date=isoBahia(),key=`anuncio:${date}:${slot}`;if(await get('SELECT 1 FROM envios_automaticos WHERE chave=?',[key]))return;const next=await nextAvailableDate(date);if(!next)return;const campaign=await currentCampaign(date);const intro=campaign?.texto||(slot==='07'?'☀️ Bom dia, Harmony Residence! A agenda do Harmony Car Wash está aberta.':'🚗 Ainda quer deixar seu carro limpo hoje? Confira os horários disponíveis.');const when=next.date===date?'hoje':`em ${next.date.split('-').reverse().join('/')}`;const free=next.free.join(', ');const link=bookingLink();const text=`${intro}\n\n📅 Próxima disponibilidade: *${when}*\n⏰ Horários: ${free}\n\nSeu carro limpo sem sair de casa. 🏠${link?`\n\n👉 Agende aqui: ${link}`:''}`;const image=campaign?.imagem?path.join(CAMPAIGN_DIR,path.basename(campaign.imagem)):null;if(await sendGroupMessage(text,image))await run('INSERT OR IGNORE INTO envios_automaticos(chave) VALUES(?)',[key])}
async function resumePendingPayments(){const pending=await all('SELECT a.*,c.whatsapp FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id WHERE a.payment_id IS NOT NULL AND a.pagamento_status NOT IN ("paid","expired")');for(const a of pending){const paid=await checkPayment(a.id,a.payment_id,jid(a.whatsapp));if(!paid&&a.forma_pagamento===PAY_NOW&&a.status==='aguardando_pagamento'){const age=Date.now()-new Date(String(a.payment_created_at||a.created_at).replace(' ','T')+'Z').getTime();if(age>=10*60*1000){await run('UPDATE agendamentos SET pagamento_status="expired",status="cancelado" WHERE id=?',[a.id]);await send(jid(a.whatsapp),`⌛ O PIX da reserva #${a.id} expirou e o horário foi liberado.`);io.emit('refresh')}}}}
function startAutomations(){cron.schedule('0 7 * * *',()=>sendScheduledAd('07').catch(console.error),{timezone:TZ});cron.schedule('0 12 * * *',()=>sendScheduledAd('12').catch(console.error),{timezone:TZ});setInterval(()=>resumePendingPayments().catch(console.error),60*1000)}
async function startWhatsApp(){const makeWASocket=baileys.default||baileys.makeWASocket,{state,saveCreds}=await baileys.useMultiFileAuthState(SESSION);sock=makeWASocket({auth:state,logger:pino({level:'silent'}),printQRInTerminal:false});sock.ev.on('creds.update',saveCreds);sock.ev.on('connection.update',async u=>{if(u.qr){qrData=await QRCode.toDataURL(u.qr);io.emit('qr',qrData)}if(u.connection==='open'){connected=true;qrData='';io.emit('wa','connected')}if(u.connection==='close'){connected=false;setTimeout(startWhatsApp,3000)}});sock.ev.on('messages.upsert',async ev=>{for(const m of ev.messages||[]){if(!m.message||m.key.fromMe||m.key.remoteJid?.endsWith('@g.us'))continue;const text=m.message.conversation||m.message.extendedTextMessage?.text||'';await handle(m.key.remoteJid,text)}})}
app.use(express.json());
function cookie(req,name){const raw=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return raw?decodeURIComponent(raw.slice(name.length+1)):''}
const auth=async(req,res,next)=>{try{if(req.query.token&&req.query.token===settings.operation_token)return next();const token=cookie(req,'harmony_admin');if(!token)return res.status(401).json({error:'Não autorizado'});const hash=crypto.createHash('sha256').update(token).digest('hex'),s=await get('SELECT 1 FROM admin_sessions WHERE token_hash=? AND expires_at>?',[hash,Date.now()]);if(!s)return res.status(401).json({error:'Sessão expirada'});next()}catch(e){res.status(500).json({error:'Falha de autenticação'})}};
app.get('/api/setup/status',async(req,res)=>res.json({configured:!!(await get('SELECT 1 FROM admin_auth WHERE id=1'))}));
app.post('/api/setup',async(req,res)=>{if(await get('SELECT 1 FROM admin_auth WHERE id=1'))return res.status(409).json({error:'Painel já configurado'});const password=String(req.body.password||'');if(password.length<8)return res.status(400).json({error:'A senha precisa ter pelo menos 8 caracteres'});const salt=crypto.randomBytes(16).toString('hex');await run('INSERT INTO admin_auth(id,salt,hash) VALUES(1,?,?)',[salt,passwordHash(password,salt)]);await saveSetting('operation_token',crypto.randomBytes(24).toString('hex'));await saveSetting('publicar_grupo','0');res.json({ok:true})});
app.post('/api/login',async(req,res)=>{const a=await get('SELECT * FROM admin_auth WHERE id=1');if(!a||passwordHash(String(req.body.password||''),a.salt)!==a.hash)return res.status(401).json({error:'Senha incorreta'});const token=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(token).digest('hex');await run('DELETE FROM admin_sessions WHERE expires_at<=?',[Date.now()]);await run('INSERT INTO admin_sessions(token_hash,expires_at) VALUES(?,?)',[hash,Date.now()+7*86400000]);res.setHeader('Set-Cookie',`harmony_admin=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${req.headers['x-forwarded-proto']==='https'?'; Secure':''}`);res.json({ok:true})});
app.post('/api/logout',auth,async(req,res)=>{const token=cookie(req,'harmony_admin');if(token)await run('DELETE FROM admin_sessions WHERE token_hash=?',[crypto.createHash('sha256').update(token).digest('hex')]);res.setHeader('Set-Cookie','harmony_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true})});
app.post('/api/webhooks/mercadopago',async(req,res)=>{res.sendStatus(200);const pid=String(req.body?.data?.id||req.query['data.id']||'');if(!pid)return;const a=await get('SELECT a.id,c.whatsapp FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id WHERE a.payment_id=?',[pid]);if(a)checkPayment(a.id,pid,jid(a.whatsapp)).catch(console.error)});
app.get('/api/config',auth,async(req,res)=>res.json({mercadopago_configurado:!!settings.mercadopago_access_token,base_url:settings.base_url||'',whatsapp_public_number:settings.whatsapp_public_number||'',whatsapp_group_jid:settings.whatsapp_group_jid||'',publicar_grupo:settings.publicar_grupo==='1',operation_token:settings.operation_token||''}));
app.put('/api/config',auth,async(req,res)=>{const b=req.body||{};if(String(b.mercadopago_access_token||'').trim())await saveSetting('mercadopago_access_token',String(b.mercadopago_access_token).trim());await saveSetting('base_url',String(b.base_url||'').replace(/\/$/,''));await saveSetting('whatsapp_public_number',String(b.whatsapp_public_number||'').replace(/\D/g,''));await saveSetting('whatsapp_group_jid',String(b.whatsapp_group_jid||''));await saveSetting('publicar_grupo',b.publicar_grupo?'1':'0');res.json({ok:true})});
app.get('/api/grupos',auth,async(req,res)=>{if(!connected||!sock)return res.status(503).json({error:'Conecte o WhatsApp primeiro'});try{const groups=await sock.groupFetchAllParticipating();res.json(Object.values(groups).map(g=>({id:g.id,nome:g.subject})).sort((a,b)=>a.nome.localeCompare(b.nome)))}catch(e){res.status(500).json({error:'Não foi possível listar os grupos'})}});
app.use('/uploads',express.static(UP));app.use(express.static(path.join(__dirname,'public')));
app.get('/api/hoje',auth,async(req,res)=>{const date=req.query.data||isoBahia();res.json(await all(`SELECT a.*,c.nome,c.casa,c.whatsapp,v.modelo,v.cor,s.nome servico,s.preco FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id JOIN veiculos v ON v.id=a.veiculo_id JOIN servicos s ON s.id=a.servico_id WHERE a.data=? AND a.status NOT IN ('aguardando_pagamento','cancelado','erro_pagamento') ORDER BY a.horario`,[date]))});app.get('/api/qr',auth,(req,res)=>res.json({connected,qr:qrData}));
app.get('/api/campanhas',auth,async(req,res)=>{const year=Number(req.query.ano||isoBahia().slice(0,4)),dates=campaignDates(year);res.json((await all('SELECT * FROM campanhas ORDER BY rowid')).map(x=>({...x,data:dates[x.id]||null})))});
app.put('/api/campanhas/:id',auth,async(req,res)=>{const current=await get('SELECT * FROM campanhas WHERE id=?',[req.params.id]);if(!current)return res.status(404).json({error:'Campanha não encontrada'});const ativo=req.body.ativo===undefined?current.ativo:(req.body.ativo?1:0),antecedencia=Math.max(0,Math.min(30,Number(req.body.antecedencia??current.antecedencia))),texto=String(req.body.texto??current.texto).trim(),imagem=req.body.imagem===undefined?current.imagem:path.basename(String(req.body.imagem||''));if(!texto)return res.status(400).json({error:'Texto obrigatório'});await run('UPDATE campanhas SET ativo=?,antecedencia=?,texto=?,imagem=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[ativo,antecedencia,texto,imagem||null,current.id]);res.json({ok:true})});
app.post('/api/anuncios/teste',auth,async(req,res)=>{try{await sendScheduledAd(req.body.horario==='12'?'12':'07');res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,path.join(UP,req.params.tipo)),filename:(req,file,cb)=>cb(null,`${req.params.id}-${Date.now()}.jpg`)}),upload=multer({storage,limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp)$/.test(file.mimetype))});
app.post('/api/agendamento/:id/status',auth,async(req,res)=>{const a=await booking(req.params.id);if(!a)return res.sendStatus(404);const st=req.body.status;if(st==='indo'){if(a.status!=='agendado')return res.status(400).json({error:'O agendamento precisa estar confirmado'});await run('UPDATE agendamentos SET status="indo" WHERE id=?',[a.id]);await send(jid(a.whatsapp),`🚗 Estamos a caminho!\n\nNossa equipe está indo até a Casa ${a.casa}.\nPor favor, deixe o veículo disponível. 🧽`)}else if(st==='iniciar'){if(a.status!=='indo')return res.status(400).json({error:'Use primeiro o botão ESTOU INDO'});if(!a.foto_antes)return res.status(400).json({error:'Foto ANTES obrigatória'});await run('UPDATE agendamentos SET status="lavando",inicio=datetime("now","localtime") WHERE id=?',[a.id]);await send(jid(a.whatsapp),`🚿 *LAVAGEM INICIADA!*\nSeu ${a.modelo} já está sendo cuidado pelo Harmony Car Wash. ✨`)}else return res.status(400).json({error:'Status inválido'});io.emit('refresh');res.json({ok:true})});
app.post('/api/agendamento/:id/foto/:tipo',auth,upload.single('foto'),async(req,res)=>{if(!['antes','depois'].includes(req.params.tipo)||!req.file)return res.status(400).json({error:'Foto inválida'});const a=await booking(req.params.id);if(!a)return res.sendStatus(404);if(req.params.tipo==='antes'&&!['indo','lavando'].includes(a.status))return res.status(400).json({error:'Use primeiro o botão ESTOU INDO'});if(req.params.tipo==='depois'&&a.status!=='lavando')return res.status(400).json({error:'Inicie a lavagem antes da foto DEPOIS'});await run(`UPDATE agendamentos SET foto_${req.params.tipo}=? WHERE id=?`,[req.file.filename,req.params.id]);io.emit('refresh');res.json({ok:true,file:req.file.filename})});
app.post('/api/agendamento/:id/finalizar',auth,async(req,res)=>{const a=await booking(req.params.id);if(!a)return res.sendStatus(404);if(!connected||!sock)return res.status(503).json({error:'WhatsApp desconectado. Reconecte antes de finalizar'});if(a.status!=='lavando')return res.status(400).json({error:'A lavagem precisa estar em andamento'});if(!a.foto_antes||!a.foto_depois)return res.status(400).json({error:'Fotos ANTES e DEPOIS são obrigatórias'});const stamp=Date.now(),out=`${a.id}-${stamp}.jpg`,publicOut=`${a.id}-${stamp}-grupo.jpg`;await montage(a,path.join(UP,'montagens',out),false);await montage(a,path.join(UP,'montagens',publicOut),true);await run('UPDATE agendamentos SET status="finalizado",fim=datetime("now","localtime"),montagem=? WHERE id=?',[out,a.id]);const buf=fs.readFileSync(path.join(UP,'montagens',out));try{await sock.sendMessage(jid(a.whatsapp),{image:buf,caption:`✨ *LAVAGEM CONCLUÍDA!*\n\nSeu ${a.modelo} está pronto! 🚗✨\nObrigado por escolher o Harmony Car Wash! 💙\n\n⭐ Avalie nosso serviço de 1 a 5 estrelas.`})}catch(e){console.error('ENVIO CLIENTE',e.message)}const link=bookingLink();try{await sendGroupMessage(`✨ *MAIS UM FINALIZADO!* 🚗🧽\n\n🚘 ${a.modelo} — ${a.cor}\n🧽 ${a.servico}\n\nQuer deixar seu carro assim também?${link?`\n👉 ${link}`:' Chame o Harmony Car Wash no privado.'}`,path.join(UP,'montagens',publicOut))}catch(e){console.error('ENVIO GRUPO',e.message)}if(a.forma_pagamento===PAY_AFTER&&a.pagamento_status!=='paid'){const c=await get('SELECT documento FROM clientes WHERE id=?',[a.cliente_id]);try{await send(jid(a.whatsapp),'💳 Conforme escolhido no agendamento, agora enviaremos o PIX para pagamento da lavagem.')}catch(e){console.error('AVISO PIX',e.message)}await generatePix(a.id,jid(a.whatsapp),c.documento,false)}io.emit('refresh');res.json({ok:true,montagem:out})});
async function booking(id){return get(`SELECT a.*,c.nome,c.casa,c.whatsapp,v.modelo,v.cor,s.nome servico,s.preco FROM agendamentos a JOIN clientes c ON c.id=a.cliente_id JOIN veiculos v ON v.id=a.veiculo_id JOIN servicos s ON s.id=a.servico_id WHERE a.id=?`,[id])}
async function montage(a,out,publicVersion=false){const A=path.join(UP,'antes',a.foto_antes),B=path.join(UP,'depois',a.foto_depois),W=1200,H=900;const aa=await sharp(A).resize(600,650,{fit:'cover'}).jpeg().toBuffer(),bb=await sharp(B).resize(600,650,{fit:'cover'}).jpeg().toBuffer();const privacy=publicVersion?'<rect x="190" y="570" width="220" height="85" rx="18" fill="#102b4e" fill-opacity="0.94"/><rect x="790" y="570" width="220" height="85" rx="18" fill="#102b4e" fill-opacity="0.94"/><text x="220" y="622" fill="white" font-size="22" font-family="Arial" font-weight="700">PRIVACIDADE</text><text x="820" y="622" fill="white" font-size="22" font-family="Arial" font-weight="700">PRIVACIDADE</text>':'';const svg=Buffer.from(`<svg width="${W}" height="${H}"><rect width="100%" height="130" fill="#0f2747"/><text x="60" y="65" fill="white" font-size="42" font-family="Arial" font-weight="700">HARMONY CAR WASH</text><text x="60" y="108" fill="#cfe8ff" font-size="24" font-family="Arial">Harmony Residence • ${a.modelo} — ${a.cor}</text>${privacy}<rect y="780" width="100%" height="120" fill="#0f2747"/><text x="180" y="850" fill="white" font-size="36" font-family="Arial" font-weight="700">ANTES</text><text x="850" y="850" fill="white" font-size="36" font-family="Arial" font-weight="700">DEPOIS</text></svg>`);await sharp({create:{width:W,height:H,channels:3,background:'#f8fafc'}}).composite([{input:aa,left:0,top:130},{input:bb,left:600,top:130},{input:svg,left:0,top:0}]).jpeg({quality:90}).toFile(out)}
app.get('/operacao',auth,(req,res)=>res.sendFile(path.join(__dirname,'public','operacao.html')));app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.get('/health',(req,res)=>res.json({ok:true,whatsapp:connected,configured:!!settings.operation_token}));
init().then(()=>{server.listen(PORT,()=>console.log('Harmony Car Wash na porta',PORT));startWhatsApp();startAutomations();resumePendingPayments().catch(console.error)}).catch(console.error);
